version: '2'
services:
  redis:
    image: redis
    volumes:
      - wttrData:/data
  wttr-proxy:
    image: sigmification/wttr-proxy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    stdin_open: true
    tty: true
    links:
      - redis:redis
    labels:
      io.rancher.container.pull_image: always
  letsencrypt:
    image: janeczku/rancher-letsencrypt:v0.5.0
    environment:
      API_VERSION: Production
      AURORA_ENDPOINT: ''
      AURORA_KEY: ''
      AURORA_USER_ID: ''
      AWS_ACCESS_KEY: ''
      AWS_SECRET_KEY: ''
      AZURE_CLIENT_ID: ''
      AZURE_CLIENT_SECRET: ''
      AZURE_RESOURCE_GROUP: ''
      AZURE_SUBSCRIPTION_ID: ''
      AZURE_TENANT_ID: ''
      CERT_NAME: wttr.pluszczewski.pl
      CLOUDFLARE_EMAIL: ''
      CLOUDFLARE_KEY: ''
      DNSIMPLE_EMAIL: ''
      DNSIMPLE_KEY: ''
      DNS_RESOLVERS: 8.8.8.8:53,8.8.4.4:53
      DOMAINS: wttr.pluszczewski.pl
      DO_ACCESS_TOKEN: ''
      DYN_CUSTOMER_NAME: ''
      DYN_PASSWORD: ''
      DYN_USER_NAME: ''
      EMAIL: lukasz.pluszczewski@gmail.com
      EULA: 'Yes'
      GANDI_API_KEY: ''
      NS1_API_KEY: ''
      OVH_APPLICATION_KEY: ''
      OVH_APPLICATION_SECRET: ''
      OVH_CONSUMER_KEY: ''
      PROVIDER: HTTP
      PUBLIC_KEY_TYPE: RSA-2048
      RENEWAL_PERIOD_DAYS: '20'
      RENEWAL_TIME: '12'
      RUN_ONCE: 'false'
      VULTR_API_KEY: ''
    volumes:
      - /var/lib/rancher:/var/lib/rancher
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
