version: "2"
services:
  app:
    container_name: wttr-proxy
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
  redis:
    container_name: wttr-redis
    image: redis
    ports:
      - "6379:6379"
